name: credbird
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.2
  provider: ^6.1.2
  introduction_screen: ^3.1.17
  flip_card: ^0.7.0
  font_awesome_flutter: ^10.8.0
  share_plus: ^10.1.4
  clipboard: ^0.1.3
  flutter_native_splash: ^2.4.5
  dropdown_button2: ^2.3.9
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/mastercardLogo.png
    - assets/profile.png
    - assets/appLogo.png
    - assets/payments.jpg
    - assets/remitannce.png

flutter_native_splash:
  color: "#BB86FC"
  image: assets/appLogo.png
  android: true
  ios: true
  web: false
  android_gravity: center
  ios_content_mode: center