name: credbird
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0-323.0.dev

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.2
  provider: ^6.1.2
  introduction_screen: ^3.1.17
  flip_card: ^0.7.0
  font_awesome_flutter: ^10.8.0
  share_plus: ^10.1.4
  clipboard: ^0.1.3
  flutter_native_splash: ^2.4.5
  dropdown_button2: ^2.3.9
  image_picker: ^1.1.2
  pdf: ^3.11.3
  path_provider: ^2.1.5
  open_file: ^3.5.10
  rename_app: ^1.6.2
  flutter_svg: ^2.0.17
  flutter_animate: ^4.5.2
  google_fonts: ^6.2.1
  flutter_dotenv: ^5.2.1
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/mastercardLogo.png
    - assets/profile.png
    - assets/appLogo.png
    - assets/payments.jpg
    - assets/remitannce.png
    - assets\flags\eu.svg
    - assets\flags\gb.svg
    - assets\flags\jp.svg
    - assets\flags\us.svg
    - .env

flutter_native_splash:
  color: "#BB86FC"
  image: assets/appLogo.png
  android: true
  ios: true
  web: false
  android_gravity: center
  ios_content_mode: center

flutter_icons:
  android: true
  ios: true
  image_path: "assets/appLogo.png"
